load 'deploy'
dirs = ['vendor/gems/*/recipes/*.rb','vendor/plugins/*/recipes/*.rb']
dirs.each { |dir| Dir[dir].each { |plugin| load(plugin) }}

# dev, staging, production
require 'capistrano/ext/multistage'

# color
require 'capistrano_colors'
require 'railsless-deploy'

load 'config/deploy'
